### PR TITLE
[feat] Copy as Discord timestamp

### PR DESCRIPTION
**Pull request by netux**
Adds a dropdown next to the date with an option to copy time as a [Discord timestamp (`<t:...>`)](https://discord.com/developers/docs/reference#message-formatting).

❌ I didn't bother much with the colors or checking for dark/light themes. Feel free to adjust colors as needed
✔ Tested with mobile screens
ℹ Uses FontAwesome for icons

Dropdown logic based on https://codechips.me/tailwind-ui-react-vs-svelte/ and https://tailwindui.com/components/application-ui/elements/dropdowns

image

### CODE REVIEW

**Comment by netux** [comment]
Update: mobile should work now 🎉

**Comment by CactusPuppy** [comment]
Thanks for the PR! I'm not necessarily a fan of how the icon looks in an otherwise clean UI, but maybe putting the dropdown under the date itself might look better? (i.e. the date has an arrow next to it which expands into a bigger dropdown)

**Comment by netux** [comment]
> Thanks for the PR! I'm not necessarily a fan of how the icon looks in an otherwise clean UI, but maybe putting the dropdown under the date itself might look better? (i.e. the date has an arrow next to it which expands into a bigger dropdown)

Something like this? 
image

Thought I'm still unsure on how the dropdown items should look. Any ideas?
image

**Comment by netux** [comment]
New fade-in-out animation:
chrome_IzBlegH0j6

Uses `Element.animate()` which [seems to be supported by all major browsers](https://caniuse.com/web-animation)

**Comment by CactusPuppy** [comment]
@netux I was unable to get the confirmation for "copied" to appear in Firefox. This appears to be due to Firefox not supporting `clipboard-write` as a permission name. The full error generated on Firefox is attached below.

```
Uncaught (in promise) TypeError: 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    copyToClipboard _copy_time.svelte:14
    copyDiscordTimestamp _copy_time.svelte:25
    handleClick _copy_time_button.svelte:7
    dispose _dropdown_item.svelte:10
```

Consider attempting to write to clipboard anyways in case the browser being used does not support the specified permission enum, but nonetheless supports writing to clipboard.

**Comment by netux** [comment]
Nice catch.

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) says
> The "clipboard-write" permission of the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API), is granted automatically to pages when they are in the active tab.

so the query wasn't needed anyway.

**Review by CactusPuppy — APPROVED** [review]
LGTM!

**Pull request merged**
